version: '3'

services:
  mysql:
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: <pw>
      MYSQL_DATABASE: rmt
      MYSQL_USER: rmt
      MYSQL_PASSWORD: <pw>
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d # Assuming you have a sql-scripts folder in your directory

  tomcat:
    image: tomcat:9-jdk11-openjdk-slim
    depends_on:
      - mysql
    environment:
      JPDA_ADDRESS: "*:8000"
      JPDA_TRANSPORT: dt_socket
    ports:
      - "8080:8080"
      - "8000:8000"  # Port for remote debugger
    volumes:
      - ../build/libs/das-tool.war:/usr/local/tomcat/webapps/das-tool.war
    command: catalina.sh jpda run  # Start Tomcat with remote debugging

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
