
    create table Activity (
        id bigint generated by default as identity,
        objectStatus integer,
        date timestamp,
        message blob,
        club_id bigint,
        user_id bigint,
        primary key (id)
    );

    create table Club (
        id bigint generated by default as identity,
        objectStatus integer,
        name varchar(255),
        primary key (id)
    );

    create table Event (
        eventType varchar(31) not null,
        id bigint generated by default as identity,
        objectStatus integer,
        comment varchar(255),
        date timestamp,
        invitationSent boolean,
        summary varchar(255),
        time time,
        kickoff time,
        surfaceList varchar(255),
        club_id bigint,
        createdBy_id bigint,
        team_id bigint,
        venue_id bigint,
        uniform_id bigint,
        opponent_id bigint,
        primary key (id)
    );

    create table Invitation (
        id bigint generated by default as identity,
        objectStatus integer,
        comment varchar(255),
        date timestamp,
        guestName varchar(255),
        invitationSent boolean,
        managerComment varchar(255),
        status varchar(255),
        event_id bigint,
        user_id bigint,
        primary key (id)
    );

    create table Opponent (
        id bigint generated by default as identity,
        objectStatus integer,
        name varchar(255),
        url varchar(255),
        club_id bigint,
        primary key (id),
        unique (name, club_id)
    );

    create table Player (
        id bigint generated by default as identity,
        objectStatus integer,
        notification boolean,
        optional boolean,
        retired boolean,
        team_id bigint,
        user_id bigint,
        primary key (id)
    );

    create table Role (
        id bigint generated by default as identity,
        objectStatus integer,
        authority varchar(255),
        user_id bigint,
        primary key (id),
        unique (user_id, authority)
    );

    create table Team (
        id bigint generated by default as identity,
        objectStatus integer,
        name varchar(255),
        url varchar(255),
        club_id bigint,
        primary key (id),
        unique (name, club_id)
    );

    create table Uniform (
        id bigint generated by default as identity,
        objectStatus integer,
        name varchar(255),
        shirt varchar(255),
        shorts varchar(255),
        socks varchar(255),
        team_id bigint,
        primary key (id)
    );

    create table Users (
        id bigint generated by default as identity,
        objectStatus integer,
        username varchar(255),
        enabled boolean,
        password varchar(255),
        fullname varchar(255),
        initialPassword varchar(255),
        invitationSent boolean,
        secondEmail varchar(255),
        status varchar(255),
        club_id bigint,
        primary key (id),
        unique (username),
        unique (fullname, club_id)
    );

    create table Venue (
        id bigint generated by default as identity,
        objectStatus integer,
        address varchar(255),
        lat double,
        lng double,
        name varchar(255),
        club_id bigint,
        primary key (id)
    );

    create index ix_club on Activity (club_id);

    alter table Activity 
        add constraint FKA126572FA64B977A 
        foreign key (club_id) 
        references Club;

    alter table Activity 
        add constraint FKA126572F699BC35A 
        foreign key (user_id) 
        references Users;

    create index ix_club on Event (club_id);

    alter table Event 
        add constraint FK403827A18344BBA 
        foreign key (uniform_id) 
        references Uniform;

    alter table Event 
        add constraint FK403827AE9F2D966 
        foreign key (createdBy_id) 
        references Users;

    alter table Event 
        add constraint FK403827A5CB6EDDA 
        foreign key (venue_id) 
        references Venue;

    alter table Event 
        add constraint FK403827AA64B977A 
        foreign key (club_id) 
        references Club;

    alter table Event 
        add constraint FK403827ACA4D421A 
        foreign key (opponent_id) 
        references Opponent;

    alter table Event 
        add constraint FK403827A1C96621A 
        foreign key (team_id) 
        references Team;

    create index ix_event on Invitation (event_id);

    create index ix_user on Invitation (user_id);

    create index ix_status on Invitation (status);

    alter table Invitation 
        add constraint FKBE1153B9D1F985A6 
        foreign key (event_id) 
        references Event;

    alter table Invitation 
        add constraint FKBE1153B9699BC35A 
        foreign key (user_id) 
        references Users;

    create index ix_club on Opponent (club_id);

    alter table Opponent 
        add constraint FKF8A5457DA64B977A 
        foreign key (club_id) 
        references Club;

    create index ix_retired on Player (retired);

    create index ix_notification on Player (notification);

    create index ix_user on Player (user_id);

    create index ix_team on Player (team_id);

    create index ix_optional on Player (optional);

    alter table Player 
        add constraint FK8EA38701699BC35A 
        foreign key (user_id) 
        references Users;

    alter table Player 
        add constraint FK8EA387011C96621A 
        foreign key (team_id) 
        references Team;

    create index ix_user on Role (user_id);

    alter table Role 
        add constraint FK26F496699BC35A 
        foreign key (user_id) 
        references Users;

    create index ix_club on Team (club_id);

    alter table Team 
        add constraint FK27B67DA64B977A 
        foreign key (club_id) 
        references Club;

    create index ix_team on Uniform (team_id);

    alter table Uniform 
        add constraint FK521E71941C96621A 
        foreign key (team_id) 
        references Team;

    create index ix_club on Users (club_id);

    create index ix_status on Users (status);

    create index ix_enabled on Users (enabled);

    create index ix_username on Users (username);

    alter table Users 
        add constraint FK4E39DE8A64B977A 
        foreign key (club_id) 
        references Club;

    create index ix_club on Venue (club_id);

    alter table Venue 
        add constraint FK4EB7A4FA64B977A 
        foreign key (club_id) 
        references Club;
