package de.flower.rmt.service.mail;

import de.flower.rmt.test.AbstractIntegrationTests;
import org.testng.annotations.Test;

/**
 * @author flowerrrr
 */
public class MailServiceManualTest extends AbstractIntegrationTests {

    private String mailAddress = "das-tool@flower.de";

    /**
     * Sends a mail to some real address.
     */
    @Test
    public void testSendMail() {
        String body = "This mail is generated by " + this.getClass().getName();
        body += "\nSome umlaute: äöüÄÖÜß\n";
        mailService.sendMail(null, mailAddress, "Unit test generated mail", body);
        log.info("Check mail at [" + mailAddress + "] to verify mail has been sent.");
    }

}
