package de.flower.rmt.service.mail;

import de.flower.rmt.test.AbstractIntegrationTests;
import org.testng.annotations.Test;

/**
 * @author flowerrrr
 */
public class MailServiceTest extends AbstractIntegrationTests {

    /**
     * Sends a mail to mailinator.com.
     */
    @Test
    public void testSendMail() {
        String body = "This mail is generated by " + this.getClass().getName();
        body += "\nSome umlaute: äöüÄÖÜß\n";
        mailService.sendMail(null, "das-tool-test@mailinator.com", "Unit test generated mail", body);
        log.info("Open http://das-tool-test.mailinator.com to verify mail has been sent.");
    }

}
