-- do not edit this file. it is generated by the ant-target [db-drop-base].

SET foreign_key_checks = 0;

DROP TABLE authorities;
DROP TABLE club;
DROP TABLE event;
DROP TABLE invitation;
DROP TABLE role;
DROP TABLE team;
DROP TABLE team_player;
DROP TABLE users;
DROP TABLE venue;

