-- do not edit this file. it is generated by the ant-target [db-drop-base].

SET foreign_key_checks = 0;

DROP TABLE club;
DROP TABLE event;
DROP TABLE invitation;
DROP TABLE invitee;
DROP TABLE jersey;
DROP TABLE opponent;
DROP TABLE player;
DROP TABLE role;
DROP TABLE team;
DROP TABLE users;
DROP TABLE venue;

